// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgIqATP31C-TKlsvhbc9Rn9YDq6MCwE6s',
    appId: '1:131771506123:web:3fb5817ad2294206c26a4e',
    messagingSenderId: '131771506123',
    projectId: 'prepsync-cd384',
    authDomain: 'prepsync-cd384.firebaseapp.com',
    storageBucket: 'prepsync-cd384.firebasestorage.app',
    measurementId: 'G-4M9LBT0M8K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW95VFjHNMKHNTds9zViuiRJiYkQopdmA',
    appId: '1:131771506123:android:644fccb12b3e1f90c26a4e',
    messagingSenderId: '131771506123',
    projectId: 'prepsync-cd384',
    storageBucket: 'prepsync-cd384.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdYecF70pmCKzgsNiF4mMcXMKBK8QYMkw',
    appId: '1:131771506123:ios:8af971bbc5b94a9dc26a4e',
    messagingSenderId: '131771506123',
    projectId: 'prepsync-cd384',
    storageBucket: 'prepsync-cd384.firebasestorage.app',
    iosBundleId: 'com.example.prepsync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdYecF70pmCKzgsNiF4mMcXMKBK8QYMkw',
    appId: '1:131771506123:ios:8af971bbc5b94a9dc26a4e',
    messagingSenderId: '131771506123',
    projectId: 'prepsync-cd384',
    storageBucket: 'prepsync-cd384.firebasestorage.app',
    iosBundleId: 'com.example.prepsync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgIqATP31C-TKlsvhbc9Rn9YDq6MCwE6s',
    appId: '1:131771506123:web:1f0943d7d90c7f6ec26a4e',
    messagingSenderId: '131771506123',
    projectId: 'prepsync-cd384',
    authDomain: 'prepsync-cd384.firebaseapp.com',
    storageBucket: 'prepsync-cd384.firebasestorage.app',
    measurementId: 'G-TQC71PTDRE',
  );
}
