name: prepsync
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  http: ^1.2.1 
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  firebase_core: ^3.2.0 
  firebase_auth: ^5.1.2 
  google_sign_in: ^6.2.1 
  simple_animations: ^5.0.2
  percent_indicator: ^4.2.3 
  fl_chart: ^0.68.0       
  intl: ^0.19.0 
   
            


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.0 

flutter:
  uses-material-design: true
  assets:
    - assets/


flutter_native_splash:
  color: "#00A79D"
  image: assets/logo/icon.png
  android: true
  ios: true


